// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCftof05udnESKrqe8ZJJTeisBgUzeR21Q',
    appId: '1:371002700181:web:0fc72b3d58f4a6c3da069c',
    messagingSenderId: '371002700181',
    projectId: 'cp-restaurants',
    authDomain: 'cp-restaurants.firebaseapp.com',
    storageBucket: 'cp-restaurants.appspot.com',
    measurementId: 'G-LHE16G6THT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiyHQmh7WJckAIjf0sCJGDbcTLF3Reh2E',
    appId: '1:350519552808:android:a42751682c6be7a3f03e1d',
    messagingSenderId: '350519552808',
    projectId: 'do-an-tot-nghiep-381c4',
    storageBucket: 'do-an-tot-nghiep-381c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU_uv12Mf4CnUdJq0JLwlYkOIEz8nVzv0',
    appId: '1:350519552808:ios:3d04b5e51e3418b0f03e1d',
    messagingSenderId: '350519552808',
    projectId: 'do-an-tot-nghiep-381c4',
    storageBucket: 'do-an-tot-nghiep-381c4.firebasestorage.app',
    iosBundleId: 'com.example.cpRestaurants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEmb6fd0805bN3I1a0o2GBTGNY-IBGIRw',
    appId: '1:371002700181:ios:56218cf0b4063e86da069c',
    messagingSenderId: '371002700181',
    projectId: 'cp-restaurants',
    storageBucket: 'cp-restaurants.appspot.com',
    iosBundleId: 'com.example.cpRestaurants.RunnerTests',
  );
}